resources:
- name: helm-dockerfile
  type: git
  icon: github
  tags: [vm]
  source:
    uri: https://github.com/tylerobara/harbor-helm-s3.git
    branch: main

- name: helm-image
  icon: docker
  tags: [vm]
  type: registry-image
  source:
    repository: ((registry.url))/library/helm
    username: ((registry.user))
    password: ((registry.password))

jobs:
- name: build-and-push
  plan:
    - get: helm-dockerfile
      # resource: helm-dockerfile
      tags: [vm]
      trigger: true
    - task: build-image
      privileged: true
      tags: [vm]
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        inputs:
          - name: helm-dockerfile
        outputs:
          - name: image
        params:
          CONTEXT: helm-dockerfile/dockerfiles/helm
        run:
          path: build
    - put: helm-image
      tags: [vm]
      params:
        image: image/image.tar
        version: 0.0.3